name: ns_puzzle
description: Nonstop Puzzle Game
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.17.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  flutter_easyloading: ^3.0.5
  google_sign_in: ^6.1.5
  ns_firebase_utils: ^1.1.3
  ns_utils: ^1.1.2
  flutter_signin_button: ^2.0.0
  neopop: ^1.0.2
  confetti: ^0.7.0
  flutter_animate: ^4.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true

  #ASSETS
  assets:
    - assets/images/
    - assets/icons/

