name: ns_puzzle
description: Nonstop Puzzle Game
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_easyloading: ^3.0.5
  google_sign_in: ^5.3.3
  

 
  ns_firebase_utils:
    git:
      url: https://github.com/ProjectAJ14/ns_firebase_utils
      ref: master

  ns_utils:
    git:
      url: https://github.com/ajaykumargithub2114/ns_utils
      ref: ajay/feat/flutter-302
  flutter_signin_button: ^2.0.0
  neopop: ^1.0.2
  confetti: ^0.7.0
  flutter_animate: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0

flutter:

  uses-material-design: true

  #ASSETS
  assets:
    - assets/images/
    - assets/icons/

